jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3307/springboot_test
  username: root
  password: ye7758258

spring:
  application:
    name: springboot
  profiles:
    active: dev

#日志记录级别
logging:
    level:
      com.itheima: debug
      org.springframework: info
